### ISSUE TITLE
Headers not passing through

### ISSUE THREAD

**Issue by felipe-chamas** [AccelByte/accelbyte-typescript-sdk#1]
I was trying to authenticate users logging in with `exchangeAuthorizationCode`, but it was not working with a `Public IAM Client` and with a `Confidential IAM Client` this is prompted:

![image](https://user-images.githubusercontent.com/49691924/231538296-f48e2ef8-e549-485f-adfa-ade0bc27f589.png)

After passing the `clientId` and `clientSecret` as user/pass, the requests start to add the `Authorization: Basic ...` header. When I try to include this header as override, it also does not work.

In [these lines](https://github.com/AccelByte/accelbyte-web-sdk/blob/main/packages/sdk-iam/src/custom/clients/IamUserAuthorizationClient.ts#L86~L94), the headers from `this.conf.headers` are replaced

```ts
  const config = {
      ...this.conf,
      headers: {
        'Device-Id': deviceId,
        'Device-Name': platform.name ? platform.name.toString() : '',
        'Device-Os': platform.os ? platform.os.toString() : '',
        'Device-Type': SdkDevice.getType()
      }
    }
```

It should be:
```ts
  const config = {
      ...this.conf,
      headers: {
        'Device-Id': deviceId,
        'Device-Name': platform.name ? platform.name.toString() : '',
        'Device-Os': platform.os ? platform.os.toString() : '',
        'Device-Type': SdkDevice.getType(),
        ...this.conf.headers
      }
    }
```

**Comment by accelbyte-sdk** [comment]
Solved in [here](https://github.com/AccelByte/accelbyte-web-sdk/blob/main/packages/sdk-iam/src/custom/clients/IamUserAuthorizationClient.ts#L93C29-L93C29)
